--ANALYTICAL FUNCTION 


--SYNTAX 

--FUNCTION() OVER (PARTITION BY column ORDER BY column)

--1) ROW_NUMBER 


--Row number department-wise

SELECT EMP_ID, FIRST_NAME, DEPARTMENT_ID, SALARY,
       ROW_NUMBER() OVER (ORDER BY SALARY DESC) AS ROW_NO
FROM EMPLOYEE;

--Display row number by salary (highest first)

SELECT EMP_ID, FIRST_NAME, SALARY,
       ROW_NUMBER() OVER (ORDER BY SALARY DESC) AS RN
FROM EMPLOYEE;

--2) RANK 

--Rank employees by salary

SELECT EMP_ID, FIRST_NAME, SALARY,
       RANK() OVER (ORDER BY SALARY DESC) AS SAL_RANK
FROM EMPLOYEE;

--Employees having rank 1 salary

SELECT * FROM (
    SELECT EMP_ID, FIRST_NAME, SALARY,
           RANK() OVER (ORDER BY SALARY DESC) AS SAL_RANK
    FROM EMPLOYEE
)
WHERE SAL_RANK = 1;

--3) DENSE_RANK


--2nd highest salary employee

SELECT * FROM (
    SELECT EMP_ID, FIRST_NAME, SALARY,
           DENSE_RANK() OVER (ORDER BY SALARY DESC) AS DR
    FROM EMPLOYEE
)
WHERE DR = 2;

--ALL 3 COMBINED 


SELECT EMP_ID, FIRST_NAME, SALARY,
       ROW_NUMBER() OVER (ORDER BY SALARY DESC) AS RN,
       RANK()       OVER (ORDER BY SALARY DESC) AS R,
       DENSE_RANK() OVER (ORDER BY SALARY DESC) AS DR
FROM EMPLOYEE;

-- DEPARTMENT RANKER

SELECT * FROM (
    SELECT EMP_ID, FIRST_NAME, DEPARTMENT_ID, SALARY,
           RANK() OVER (
               PARTITION BY DEPARTMENT_ID
               ORDER BY SALARY DESC
           ) AS R
    FROM EMPLOYEE
)
WHERE R = 1;

--EMPLOYEES WHO EARN ABOVE DEPARTMENT AVERAGE BUT BELOW COMPANY AVERAGE

SELECT EMP_ID, FIRST_NAME, DEPARTMENT_ID, SALARY
FROM (
    SELECT EMP_ID, FIRST_NAME, DEPARTMENT_ID, SALARY,
           AVG(SALARY) OVER (PARTITION BY DEPARTMENT_ID) AS DEPT_AVG,
           AVG(SALARY) OVER () AS COMPANY_AVG
    FROM EMPLOYEE
)
WHERE SALARY > DEPT_AVG
  AND SALARY < COMPANY_AVG;

--TOP 2 PAID EMPLOYEES PER DEPARTMENT,

SELECT * FROM (
    SELECT EMP_ID, FIRST_NAME, DEPARTMENT_ID, SALARY,
           DENSE_RANK() OVER (
               PARTITION BY DEPARTMENT_ID
               ORDER BY SALARY DESC
           ) AS DR
    FROM EMPLOYEE
)
WHERE  DR <= 2;


--FIND EMPLOYEES WHOSE SALARY INCREASES RELATIVE TO PREVIOUS HIRE

SELECT EMP_ID, FIRST_NAME, SALARY, HIRE_DATE
FROM (
    SELECT EMP_ID, FIRST_NAME, SALARY, HIRE_DATE,
           LAG(SALARY) OVER (ORDER BY HIRE_DATE) AS PREV_SAL
    FROM EMPLOYEE
)
WHERE SALARY > PREV_SAL;

--EMPLOYEES PAID MORE THAN ALL EMPLOYEES IN OTHER DEPARTMENTS

SELECT EMP_ID, FIRST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEE E
WHERE SALARY >
      ALL (
          SELECT SALARY
          FROM EMPLOYEE
          WHERE DEPARTMENT_ID <> E.DEPARTMENT_ID
      );

