--FUNCTIONS

--SINGLE ROW FUNCTIONS

--1) CHARACTER (STRING) FUNCTION

-- CONVERT FIRST NAME TO UPPERCASE AND EMAIL TO LOWERCASE
SELECT UPPER(FIRST_NAME),LOWER(EMAIL) FROM EMPLOYEE;

-- LENGTH OF FIRST NAME
SELECT FIRST_NAME, LENGTH(FIRST_NAME) FROM EMPLOYEE;

-- FIRST 4 LETTERS OF EMPLOYEE NAME
SELECT SUBSTR(FIRST_NAME, 1, 4) FROM EMPLOYEE;

-- COMBINE FIRST NAME AND EMAIL
SELECT CONCAT(FIRST_NAME, EMAIL) FROM EMPLOYEE;

-- REMOVE SPACES FROM DEPARTMENT NAME
SELECT TRIM(DEPARTMENT_NAME) FROM DEPARTMENTS;

--2) NUMERIC FUNCTION

-- ROUND SALARY TO NEAREST THOUSAND
SELECT FIRST_NAME, ROUND(SALARY, -3) FROM EMPLOYEE;

-- SALARY ROUNDED UP AND DOWN
SELECT FIRST_NAME, CEIL(SALARY), FLOOR(SALARY) FROM EMPLOYEE;

-- FIND REMAINDER OF SALARY DIVIDED BY 1000
SELECT FIRST_NAME, MOD(SALARY, 1000) FROM EMPLOYEE;

-- ABSOLUTE SALARY DIFFERENCE
SELECT ABS(SALARY - 50000) FROM EMPLOYEE;


--3) DATE FUNCTION

-- CURRENT SYSTEM DATE
SELECT SYSDATE FROM DUAL;

-- NUMBER OF MONTHS EMPLOYEE HAS WORKED
SELECT FIRST_NAME, MONTHS_BETWEEN(SYSDATE, HIRE_DATE) FROM EMPLOYEE;

-- EMPLOYEE JOINING DATE + 6 MONTHS
SELECT FIRST_NAME, ADD_MONTHS(HIRE_DATE, 6) FROM EMPLOYEE;

-- NEXT MONDAY AFTER HIRE DATE
SELECT FIRST_NAME, NEXT_DAY(HIRE_DATE, 'MONDAY') FROM EMPLOYEE;


--4) COVERSION FUNCTION 

-- CONVERT HIRE DATE TO STRING FORMAT
SELECT FIRST_NAME, TO_CHAR(HIRE_DATE, 'DD-MM-YYYY') FROM EMPLOYEE;

-- CONVERT STRING TO DATE
SELECT TO_DATE('15-08-2024', 'DD-MM-YYYY') FROM DUAL;

-- CONVERT STRING TO NUMBER
SELECT TO_NUMBER('25000') FROM DUAL;


--5) GENERAL / CONDITIONAL FUNCTIONS

-- REPLACE NULL SALARY WITH 0
SELECT FIRST_NAME, NVL(SALARY, 0) FROM EMPLOYEE;

-- FIRST NON-NULL VALUE
SELECT FIRST_NAME, COALESCE(SALARY, 0) FROM EMPLOYEE;

-- SALARY GRADE USING CASE
SELECT FIRST_NAME,
       CASE
           WHEN SALARY >= 7000 THEN 'HIGH'
           WHEN SALARY >= 4000 THEN 'MEDIUM'
           ELSE 'LOW'
       END AS SALARY_GRADE
FROM EMPLOYEE;


--MULTI ROW FUNCTION

--1) SUM()

--TOTAL SALARY OF ALL EMPLOYEE COMBINED
SELECT SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE;

--2) AVG()

-- AVERAGE SALARY
SELECT AVG(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE;

--2) COUNT()

-- EMPLOYEE COUNT
SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE;

--3) MAX()

--MAXIMUM SALARY 

SELECT MAX(SALARY) AS HIGHEST_SALARY
FROM EMPLOYEE;

--4) MIN()

--MINIMUM SALARY 

SELECT MIN(SALARY) AS LOWEST_SALARY
FROM EMPLOYEE;

