
--EMPLOYEE TABLE IMPORT FROM EXCEL
SELECT * FROM EMPLOYEE;

--DEPARTMENT TABLE 
CREATE TABLE DEPARTMENTS (DEPARTMENT_ID NUMBER PRIMARY KEY,DEPARTMENT_NAME VARCHAR2(30) NOT NULL,LOCATION VARCHAR2(30));


INSERT INTO DEPARTMENTS VALUES (10, 'Administration', 'Mumbai');
INSERT INTO DEPARTMENTS VALUES (20, 'Marketing', 'Pune');
INSERT INTO DEPARTMENTS VALUES (30, 'Purchasing', 'Delhi');
INSERT INTO DEPARTMENTS VALUES (40, 'Human Resources', 'Bangalore');
INSERT INTO DEPARTMENTS VALUES (50, 'IT', 'Hyderabad');
INSERT INTO DEPARTMENTS VALUES (60, 'Finance', 'Chennai');
INSERT INTO DEPARTMENTS VALUES (70, 'Sales', 'Kolkata');
INSERT INTO DEPARTMENTS VALUES (80, 'Operations', 'Noida');
INSERT INTO DEPARTMENTS VALUES (90, 'Executive', 'Mumbai');

SELECT * FROM DEPARTMENTS;

--GROUP BY

--Average salary per department

SELECT DEPARTMENT_ID, AVG(SALARY)FROM EMPLOYEE GROUP BY DEPARTMENT_ID;

--Total salary per job

SELECT JOB_ID, SUM(SALARY) FROM EMPLOYEE GROUP BY JOB_ID;


--ORDER BY

--Employees ordered by salary (ascending)

SELECT EMP_ID, FIRST_NAME, SALARY FROM EMPLOYEE ORDER BY SALARY;

--Employees ordered by salary (decending)

SELECT EMP_ID, FIRST_NAME, SALARY FROM EMPLOYEE ORDER BY SALARY  DESC;

--ORDER BY WITH GROUP BY 
SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEE GROUP BY DEPARTMENT_ID ORDER BY AVG(SALARY) DESC;


--GROUP BY WITH HAVING 


--Departments with average salary > 10000    

SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEE GROUP BY DEPARTMENT_ID HAVING AVG(SALARY) > 10000;

--Jobs having more than 3 employees
SELECT JOB_ID, COUNT(*) FROM EMPLOYEE GROUP BY JOB_ID HAVING COUNT(*) > 3;

