--EMPLOYEE TABLE IMPORT FROM EXCEL
SELECT * FROM EMPLOYEE;

--DEPARTMENT TABLE 
CREATE TABLE DEPARTMENTS (DEPARTMENT_ID NUMBER PRIMARY KEY,DEPARTMENT_NAME VARCHAR2(30) NOT NULL,LOCATION VARCHAR2(30));


INSERT INTO DEPARTMENTS VALUES (10, 'Administration', 'Mumbai');
INSERT INTO DEPARTMENTS VALUES (20, 'Marketing', 'Pune');
INSERT INTO DEPARTMENTS VALUES (30, 'Purchasing', 'Delhi');
INSERT INTO DEPARTMENTS VALUES (40, 'Human Resources', 'Bangalore');
INSERT INTO DEPARTMENTS VALUES (50, 'IT', 'Hyderabad');
INSERT INTO DEPARTMENTS VALUES (60, 'Finance', 'Chennai');
INSERT INTO DEPARTMENTS VALUES (70, 'Sales', 'Kolkata');
INSERT INTO DEPARTMENTS VALUES (80, 'Operations', 'Noida');
INSERT INTO DEPARTMENTS VALUES (90, 'Executive', 'Mumbai');

SELECT * FROM DEPARTMENTS;

--JOINS


--1. INNER JOIN

SELECT E.EMP_ID, E.FIRST_NAME, D.DEPARTMENT_NAME FROM EMPLOYEE E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


--2. LEFT OUTER JOIN

SELECT E.EMP_ID, E.FIRST_NAME, D.DEPARTMENT_NAME FROM EMPLOYEE E LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


--3. RIGHT OUTER JOIN

SELECT E.EMP_ID, E.FIRST_NAME, D.DEPARTMENT_NAME FROM EMPLOYEE E RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


--4. FULL OUTER JOIN

SELECT E.EMP_ID, E.FIRST_NAME, D.DEPARTMENT_NAME FROM EMPLOYEE E FULL OUTER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--5. CROSS JOIN

SELECT E.FIRST_NAME, D.DEPARTMENT_NAME FROM EMPLOYEE E CROSS JOIN DEPARTMENTS D;


--6. SELF JOIN

SELECT E.FIRST_NAME AS EMPLOYEE, M.FIRST_NAME AS MANAGER FROM EMPLOYEE E JOIN EMPLOYEE M ON E.MANAGER_ID = M.EMP_ID;


--7. NATURAL JOIN

SELECT EMP_ID, FIRST_NAME, DEPARTMENT_NAME FROM EMPLOYEE NATURAL JOIN DEPARTMENTS;

--8.NON-EQUI JOIN
--GREATER THEN 

SELECT E.EMP_ID, E.FIRST_NAME, D.DEPARTMENT_NAME FROM EMPLOYEE E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID > D.DEPARTMENT_ID;

--BETWEEN 
SELECT E.EMP_ID, E.FIRST_NAME, D.DEPARTMENT_NAME FROM EMPLOYEE E, DEPARTMENTS D 
WHERE E.DEPARTMENT_ID BETWEEN 30 AND 80 AND D.DEPARTMENT_ID BETWEEN 30 AND 80;

--SET OPERATIONS 
--1. UNION

SELECT DEPARTMENT_ID FROM EMPLOYEE WHERE DEPARTMENT_ID = 60
UNION
SELECT DEPARTMENT_ID FROM EMPLOYEE WHERE DEPARTMENT_ID = 90;

--2. UNION ALL

SELECT DEPARTMENT_ID FROM EMPLOYEE WHERE DEPARTMENT_ID = 60
UNION ALL
SELECT DEPARTMENT_ID FROM EMPLOYEE WHERE DEPARTMENT_ID = 90;


--3. INTERSECT

SELECT EMP_ID FROM EMPLOYEE WHERE DEPARTMENT_ID = 90
INTERSECT
SELECT EMP_ID FROM EMPLOYEE WHERE SALARY > 10000;

--4. MINUS

SELECT JOB_ID FROM EMPLOYEE WHERE DEPARTMENT_ID = 60
MINUS
SELECT JOB_ID FROM EMPLOYEE WHERE DEPARTMENT_ID = 90;
