--SUBQUERY

--1) SINGLE ROW SUBQUERY

--Employee earning more than employee with EMP_ID = 101

SELECT EMP_ID, FIRST_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY >
      (SELECT SALARY FROM EMPLOYEE WHERE EMP_ID = 101);
      
--Employee with minimum salary
SELECT EMP_ID, FIRST_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY =
      (SELECT MIN(SALARY) FROM EMPLOYEE);



--2) MULTI ROW SUBQUERY 

--Employees earning more than ALL employees in department 60

SELECT EMP_ID, FIRST_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY > ALL
      (SELECT SALARY
       FROM EMPLOYEE
       WHERE DEPARTMENT_ID = 60);

--Employees NOT working in department 90

SELECT EMP_ID, FIRST_NAME
FROM EMPLOYEE
WHERE DEPARTMENT_ID NOT IN
      (SELECT DEPARTMENT_ID
       FROM EMPLOYEE
       WHERE DEPARTMENT_ID = 90);
       
--Employees earning less than ALL department average salaries

SELECT EMP_ID, FIRST_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY < ALL
      (SELECT AVG(SALARY)
       FROM EMPLOYEE
       GROUP BY DEPARTMENT_ID);


--CORRELATED SUBQUERY
--Employees whose salary matches any department’s minimum salary       


SELECT EMP_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEE E1
WHERE SALARY =
      (SELECT MIN(SALARY)
       FROM EMPLOYEE E2
       WHERE E1.DEPARTMENT_ID = E2.DEPARTMENT_ID);


SELECT EMP_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM (
    SELECT EMP_ID, FIRST_NAME, SALARY, DEPARTMENT_ID,
           MIN(SALARY) OVER (PARTITION BY DEPARTMENT_ID) AS MIN_SAL
    FROM EMPLOYEE
)
WHERE SALARY = MIN_SAL;

--TOP SALARY EACH DEPARTMENT
SELECT EMP_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEE E
WHERE SALARY =
      (SELECT MAX(SALARY)
       FROM EMPLOYEE
       WHERE DEPARTMENT_ID = E.DEPARTMENT_ID);

SELECT * FROM EMPLOYEE;
SELECT MIN(SALARY) FROM EMPLOYEE;
SELECT MAX(SALARY) FROM EMPLOYEE;
